---
title: "City Divisions"
format: gfm
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, paged.print = FALSE)
```

```{r}
#| message: false
library(tidycensus)
library(data.table)
library(tidyverse)
library(ggspatial)
library(geojsonsf)
library(sf)
library(rvest)
library(janitor)
```

# City Council

```{r}
# download.file("https://data.cabq.gov/government/citycouncildistricts/CityCouncilDistricts.kmz", "data/council-districts.kmz")

# unzip("data/council-districts.kmz")
# file.rename("data/doc.kml", "data/council-districts.kml")
# file.remove("data/council-districts.kmz")
# council_dists <- st_read("data/council-districts.kml")[, -2]
# dist_num <- c(4, 7, 3, 2, 6, 9, 8, 5, 1)
# district <- paste("District", dist_num)
# council_dists$district <- district
# council_dists <- council_dists[, -1]
# st_write(council_dists, "data/abq-divisions.gpkg", layer = "council", append = F)

council_dists <- st_read("data/abq-divisions.gpkg", layer = "council")
```

```{r}
ggplot(council_dists) +
  annotation_map_tile(
    type = "osm",
    cachedir = "~/.cache/maps/",
    zoomin = -1,
    alpha = 0.5
  ) +
  geom_sf(aes(color = district), fill = NA, linewidth = 1) +
  geom_sf_text(aes(label = district)) +
  theme_void() +
  labs(title = "Albuquerque Council Districts") +
  coord_sf(crs = 32113, datum = 32113)
```

# Police commands

```{r}
#| eval: false
download.file("https://coagisweb.cabq.gov/arcgis/rest/services/public/adminboundaries/MapServer/8/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson", "data/police_commands.geojson")

police_commands <- st_read("data/police_commands.geojson")
police_commands <- clean_names(police_commands)
st_write(police_commands, "data/abq-divisions.gpkg", layer = "police")
```

```{r}
police_commands <- st_read("data/abq-divisions.gpkg", layer = "police")
```


```{r}
ggplot(police_commands) +
  annotation_map_tile(
    type = "osm",
    cachedir = "~/.cache/maps/",
    zoomin = -1,
    alpha = 0.7
  ) +
  geom_sf(aes(color = area_command), fill = NA, linewidth = 1) +
  geom_sf_text(aes(label = area_command)) +
  theme_void() +
  labs(
    title = "Albuquerque Police Command Areas",
    caption = "Source: https://data.cabq.gov"
  ) +
  coord_sf(crs = 32113, datum = 32113)
```

# Parks and Open Space

```{r}
#| eval: false
url_openspace <- "https://data.cabq.gov/community/openspace/CityOpenSpace.kmz"
download.file(url_openspace, "data/openspace.kmz")
unzip("data/openspace.kmz", exdir = "data/")
file.rename("data/doc.kml", "data/openspace.kml")
file.remove("data/openspace.kmz")

openspace <- st_read("data/openspace.kml") %>%
  clean_names(openspace)

description_html <- openspace$description
description <- map_dfr(description_html, ~ {
  table <- read_html(.x) %>% html_table()
  table[[2]]
},
.id = "id_row"
) %>%
  pivot_wider(names_from = "X1", values_from = "X2") %>%
  clean_names()

openspace <- openspace[, -2] %>%
  cbind(description) %>%
  select(-"name.1")

st_write(openspace, "data/abq-divisions.gpkg", layer = "openspace")
```

```{r}
openspace <- st_read("data/abq-divisions.gpkg", layer = "openspace")
```

```{r}
ggplot(openspace) +
  annotation_map_tile(
    type = "osm",
    cachedir = "~/.cache/maps/",
    zoomin = -1,
    alpha = 0.7
  ) +
  geom_sf(
    color = "darkgreen", linewidth = 0.5,
    aes(fill = status)
  ) +
  theme_void() +
  labs(
    title = "Albuquerque Open Space",
    caption = "Source: https://data.cabq.gov"
  ) +
  coord_sf(crs = 32113, datum = 32113)
```

```{r}
#| eval: false
url_openspace_fh_trails <- "https://data.cabq.gov/community/openspace/OpenSpaceFoothillsTrails.kmz"
download.file(url_openspace_fh_trails, "data/download.kmz")
unzip("data/download.kmz", exdir = "data/")
file.rename("data/doc.kml", "data/openspace_fh_trails.kml")
file.remove("data/download.kmz")

openspace_fh_trails <- st_read("data/openspace_fh_trails.kml") %>%
  clean_names()

description_html <- openspace_fh_trails$description

description <- map_dfr(description_html, ~ {
  table <- read_html(.x) %>% html_table()
  table[[2]]
},
.id = "id_row"
) %>%
  pivot_wider(names_from = "X1", values_from = "X2") %>%
  clean_names()

openspace_fh_trails <- openspace_fh_trails[, -2] %>%
  cbind(description) %>%
  select(-c(name, notes, length))

st_write(openspace_fh_trails, "data/abq-divisions.gpkg", layer = "openspace_fh_trails")
```

```{r}
openspace_fh_trails <- st_read("data/abq-divisions.gpkg",
  layer = "openspace_fh_trails"
)
ggplot(openspace_fh_trails %>% st_transform(32113)) +
  annotation_map_tile(
    type = "osm",
    cachedir = "~/.cache/maps/",
    zoomin = -1,
    alpha = 0.7
  ) +
  geom_sf() +
  theme_void() +
  xlim(476500, 485000) +
  labs(
    title = "Albuquerque Open Space",
    subtitle = "Foothill Trails",
    caption = "Source: https://data.cabq.gov"
  ) +
  coord_sf(crs = 32113, datum = 32113)
```

```{r}
url_parks <- "https://data.cabq.gov/community/parksandrec/parks/CityParks.kmz"

get_abq_data <- function(url, name) {
  download.file(url, "data/download.kmz")
  unzip("data/download.kmz", exdir = "data/")
  file.rename("data/doc.kml", paste0(
    "data/", name,
    ".kml"
  ))
  file.remove("data/download.kmz")
}

get_abq_data(url_parks, "parks")

parks <- st_read("data/parks.kml") %>%
  clean_names()

parks

description_html <- parks$description

description <- map_dfr(description_html, ~ {
  table <- read_html(.x) %>% html_table()
  table[[2]]
},
.id = "id_row"
) %>%
  pivot_wider(names_from = "X1", values_from = "X2") %>%
  clean_names()

description

parks <- parks[, -2] %>%
  cbind(description) %>%
  select(-name)

st_write(parks, "data/abq-divisions.gpkg", layer = "parks")
```

```{r}
parks <- st_read("data/abq-divisions.gpkg", layer = "parks")

ggplot(parks %>% st_transform(32113)) +
  annotation_map_tile(
    type = "osm",
    cachedir = "~/.cache/maps/",
    zoomin = -1,
    alpha = 0.7
  ) +
  geom_sf(aes(fill = park_status), color = "lightgreen", linewidth = 0.5) +
  theme_void() +
  labs(
    title = "Albuquerque Parks",
    caption = "Source: https://data.cabq.gov"
  )
```

```{r}
ggplot(parks %>% st_transform(32113)) +
  annotation_map_tile(
    type = "osm",
    cachedir = "~/.cache/maps/",
    zoomin = -1,
    alpha = 0.7
  ) +
  geom_sf(aes(fill = park_status),
    color = "darkgreen", linewidth = 0.5
  ) +
  geom_sf(
    data = openspace, aes(fill = status),
    color = "lightgreen", linewidth = 0.5
  ) +
  theme_void() +
  labs(
    title = "Albuquerque Parks and Open Space",
    caption = "Source: https://data.cabq.gov"
  )
```


```{r}
url_neighborhoods <- "https://data.cabq.gov/community/neighborhoods/NeighborhoodAssociations.kmz"

get_abq_data(url_neighborhoods, "neighborhoods")

neighborhoods <- st_read("data/neighborhoods.kml") %>%
  select(-2)

nrow(neighborhoods)
st_write(parks, "data/abq-divisions.gpkg", layer = "parks")
```

```{r}
ggplot(neighborhoods %>% st_transform(32113)) +
  annotation_map_tile(
    type = "osm",
    cachedir = "~/.cache/maps/",
    zoomin = -1,
    alpha = 0.7
  ) +
  geom_sf(fill = NA, color = "red", linewidth = 0.5) +
  theme_void() +
  labs(
    title = "Albuquerque Neighborhood Associations",
    caption = "Source: https://data.cabq.gov"
  )
```

```{r}
url_address <- "https://data.cabq.gov/business/addressatlas/addressatlaspagegrid.kmz"

get_abq_data(url_address, "address")

address_grid <- st_read("data/address.kml") %>%
  clean_names()
address_grid
description_html <- address_grid$description

description <- map_dfr(description_html, ~ {
  table <- read_html(.x) %>% html_table()
  table[[2]]
},
.id = "id_row"
) %>%
  pivot_wider(names_from = "X1", values_from = "X2") %>%
  clean_names() %>%
  select(zonemapname)

address_grid <-
  address_grid[, -2] %>% cbind(description)
```


```{r}
ggplot(address_grid) +
  annotation_map_tile(
    type = "osm",
    cachedir = "~/.cache/maps/",
    zoomin = -1,
    alpha = 0.7
  ) +
  geom_sf(fill = NA, color = "red", linewidth = 0.5) +
  geom_sf_text(aes(label = name), color = "black") +
  ylim(450000, 465500) +
  xlim(455000, 480000) +
  theme_void() +
  labs(
    title = "Albuquerque Square Mile Grid",
    caption = "Source: https://data.cabq.gov"
  )
```

```{r}
address_grid <- address_grid %>% st_transform(32113)
```

